import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from '@/components/shared/sidebar'
import Footer from '@/components/shared/Footer'
import SearchComponent from '@/components/shared/search'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-white">
        <main className="flex flex-row">
          <Sidebar />
          <SearchComponent/>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
