import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import SideBar from "@/components/shared/sidebar";
import Footer from "@/components/shared/Footer";
import SearchComponent from "@/components/shared/search";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Complaint Register",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white max-w-[1920] max-h-screen">
        <SearchComponent />
        <div className="flex">
          <SideBar />
          <main className="flex flex-col justify-center items-center">{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
