import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import SideBar from "@/components/shared/sidebar";
import Footer from "@/components/shared/Footer";
import SearchComponent from "@/components/shared/search";
import Terms from "@/components/shared/terms";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Complaint Register",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`xl:bg-[url('/assets/bgrd.jpg')] lg:bg-[url('/assets/bgrd.jpg')] bg-center bg-cover backdrop-blur-md rounded-3xl max-w-[1920px]`}
      >
        <div className="glassmorphism rounded-3xl xl:m-3 lg:m-3 shadow-xl">
          <div className="grid xl:grid-cols-[15rem,1fr] lg:grid-cols-[15rem,1fr]">
            <SearchComponent />
            <SideBar />
            <main className="flex flex-col justify-center items-center">
              {children}
              <Toaster position="top-center" reverseOrder={false} />
            </main>
          </div>
          <Terms />
        </div>
        <Footer />
      </body>
    </html>
  );
}
